Temporary work around for MESS missing declarations
This works around MESS failing to build due to...

ui.c:(.text+0x6281): undefined reference to `hide_nagscreen'
ui.c:(.text+0x628b): undefined reference to `hide_infoscreen'
ui.c:(.text+0x6292): undefined reference to `hide_warnings'

... despite the fact that these are defined. MAME already works fine so I need to find why MESS specifically doesn't think these are defined.